# Generated by Django 5.2.1 on 2025-06-18 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('school_id', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='subjects', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
