# Generated by Django 5.2.1 on 2025-06-18 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_covers/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lead_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_mark',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('Gr8', 'Grade 8'), ('Gr9', 'Grade 9'), ('Gr10', 'Grade 10'), ('Gr11', 'Grade 11'), ('Gr12', 'Grade 12')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
