# Generated by Django 5.2.1 on 2025-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discussionthread_discussionmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='discussionmessage',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
