# Generated by Django 5.2.1 on 2025-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
