# Generated by Django 5.2.1 on 2025-07-05 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subjecttest_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='drafting_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
