# Generated by Django 5.2.1 on 2025-07-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_draftingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftingCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drafting/canvas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='core.draftingsession')),
            ],
        ),
    ]
