# Generated by Django 5.2.1 on 2025-07-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_draftingcanvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftingcanvas',
            name='image',
            field=models.ImageField(upload_to='drafting_canvases/'),
        ),
    ]
