# Generated by Django 5.2.1 on 2025-07-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_draftingcanvas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftingcanvas',
            name='image',
            field=models.ImageField(upload_to='drafting_canvas/'),
        ),
    ]
