# Generated by Django 5.2.1 on 2025-07-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_draftingcanvas_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftingsession',
            name='canvas_image',
            field=models.ImageField(blank=True, null=True, upload_to='draft_canvas/'),
        ),
        migrations.AlterField(
            model_name='draftingsession',
            name='pdf_file',
            field=models.FileField(upload_to='draft_pdfs/'),
        ),
        migrations.AlterField(
            model_name='draftingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL),
        ),
    ]
