# Generated by Django 5.2.1 on 2025-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_draftingsession_canvas_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, choices=[('Gr8', 'Grade 8'), ('Gr9', 'Grade 9'), ('Gr10', 'Grade 10'), ('Gr11', 'Grade 11'), ('Gr12', 'Grade 12')], max_length=20, null=True),
        ),
    ]
