# Generated by Django 5.2.1 on 2025-07-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number for password recovery.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Optional secondary email for account recovery.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
