# Generated by Django 5.2.1 on 2025-07-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_user_phone_remove_user_recovery_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recovery_hint',
        ),
    ]
