# Generated by Django 5.2.1 on 2025-08-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_phone_number_user_recovery_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='CanvasPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='canvas_pages/')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.draftingsession')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('draft', 'page_number')},
            },
        ),
    ]
