# Generated by Django 5.2.1 on 2025-08-05 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_email_canvaspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='conversions/originals/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='conversions/converted/')),
                ('conversion_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
