# Generated by Django for school freeze feature
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_documentconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, null=True, max_length=254)),
                ('frozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school', related_name='users'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school', related_name='subjects'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_id',
        ),
    ]
