# Generated by Django 5.2.6 on 2025-09-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_colledgesubjectassignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colledgesubjecttest',
            name='open',
            field=models.BooleanField(default=False, help_text='If open, students can take the test.'),
        ),
    ]
