# Generated by Django 5.2.6 on 2025-09-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_school_and_freeze'),
        ('core', '0037_sitelogo'),
    ]

    operations = [
    ]
