# Generated by Django 5.2.6 on 2025-09-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_0032_school_and_freeze_0037_sitelogo'),
        ('core', '0039_school_fk_and_freeze'),
    ]

    operations = [
    ]
